-- MySQL bulk insert statements for table: schools
-- Generated on: 2025-07-12T23:15:22.222Z
-- Total records: 250

CREATE TABLE IF NOT EXISTS `schools` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `school_name` VARCHAR(100),
  `school_district` VARCHAR(100),
  `school_type` VARCHAR(100),
  `grade_level` VARCHAR(100),
  `is_deleted` INT
);

-- Batch 1 of 3
INSERT INTO `schools` (`id`, `school_name`, `school_district`, `school_type`, `grade_level`, `is_deleted`) VALUES
(10, 'Shanahan and Sons', 'Cicerocester', 'charter', '9-12', 0),
(11, 'Heaney, Boyle and Jast', 'Lake Jamie', 'high', 'K-12', 0),
(12, 'Nader, Miller and Parisian', 'Blickhaven', 'private', '9-12', 0),
(13, 'Emmerich - Lind', 'Conroyville', 'elementary', 'K-12', 0),
(14, 'Erdman Group', 'Trudiemouth', 'charter', 'K-12', 0),
(15, 'Zemlak, Senger and Mante', 'Tinley Park', 'high', '6-8', 0),
(16, 'Hilpert - Blick', 'North Ocie', 'high', '6-8', 0),
(17, 'Gerhold - Bechtelar', 'Kobycester', 'charter', 'K-12', 0),
(18, 'Kshlerin - Klocko', 'Bridgeport', 'elementary', '6-8', 0),
(19, 'Franecki - Schneider', 'New Brunswick', 'high', 'K-5', 0),
(20, 'Ziemann and Sons', 'West Rogelio', 'middle', 'K-5', 0),
(21, 'Legros, Dickinson and Jacobson', 'Oberbrunnerview', 'public', 'K-5', 0),
(22, 'Daugherty, Orn and Jenkins', 'West Earl', 'middle', 'K-5', 0),
(23, 'Reichert - Altenwerth', 'Wittingchester', 'high', '6-8', 0),
(24, 'Gusikowski, Aufderhar and Spencer', 'East Alec', 'private', '6-8', 0),
(25, 'Schuppe - Wisoky', 'Marvincester', 'public', '6-8', 0),
(26, 'Moore Inc', 'Horacioworth', 'charter', 'K-12', 0),
(27, 'Daugherty, Parker and Nader', 'Bowling Green', 'high', 'K-5', 0),
(28, 'Rice Inc', 'Joeybury', 'high', 'K-12', 0),
(29, 'Jaskolski, Blick and Mante', 'Devanville', 'high', 'K-12', 0),
(30, 'Buckridge, Breitenberg and Schulist', 'South Connormouth', 'charter', '9-12', 0),
(31, 'Weimann Group', 'West Sage', 'private', 'K-5', 0),
(32, 'Torphy Inc', 'Baytown', 'private', '6-8', 0),
(33, 'Kautzer - Mraz', 'North Richland Hills', 'charter', '6-8', 0),
(34, 'McLaughlin, Gutkowski and Moore', 'Marquardtmouth', 'public', '6-8', 0),
(35, 'Kuhic and Sons', 'Goodyear', 'public', 'K-12', 0),
(36, 'Davis - Haley', 'Pomona', 'charter', '6-8', 0),
(37, 'Schaefer, Weber and Bergnaum', 'South Zechariahtown', 'public', '6-8', 0),
(38, 'Will Group', 'Lake Lilianchester', 'high', '9-12', 0),
(39, 'Gibson Inc', 'Walnut Creek', 'middle', 'K-12', 0),
(40, 'Nader LLC', 'Fort Terrance', 'private', 'K-5', 0),
(41, 'Upton - Schinner', 'Fort Baronport', 'public', '9-12', 0),
(42, 'Baumbach, Dickinson and Volkman', 'Tamiastead', 'middle', 'K-12', 0),
(43, 'Monahan Inc', 'Wyattborough', 'elementary', '9-12', 0),
(44, 'Bartoletti - Zieme', 'Whiteville', 'charter', '9-12', 0),
(45, 'Muller - Rath', 'Lake Marceloport', 'private', '6-8', 0),
(46, 'Larson - Hand', 'Davidstead', 'middle', '9-12', 0),
(47, 'Harber - Turcotte', 'Kuhlmanland', 'private', '6-8', 0),
(48, 'Price - Renner', 'Fort Hesterberg', 'private', 'K-12', 0),
(49, 'Langworth Inc', 'Lake Hoythaven', 'private', 'K-12', 0),
(50, 'Adams - Crist', 'Port Rupert', 'public', 'K-5', 0),
(51, 'Kuhn Inc', 'New Britain', 'high', 'K-5', 0),
(52, 'Kassulke - Towne', 'East Fausto', 'high', 'K-5', 0),
(53, 'Monahan LLC', 'Fort Rodger', 'charter', 'K-5', 0),
(54, 'Schaefer, Heathcote and Wyman', 'North Libby', 'elementary', 'K-5', 0),
(55, 'Fay and Sons', 'North Otisstead', 'high', 'K-5', 0),
(56, 'Okuneva LLC', 'Franzburgh', 'elementary', 'K-5', 0),
(57, 'Moore - Ledner', 'Ullrichstead', 'elementary', '6-8', 0),
(58, 'Torp Group', 'Kerlukeburgh', 'high', '9-12', 0),
(59, 'Harber - Casper', 'Veronaworth', 'public', '9-12', 0),
(60, 'Hudson - Welch', 'Waldohaven', 'charter', '9-12', 0),
(61, 'Pollich, Franey and Kub', 'New Millerville', 'high', '9-12', 0),
(62, 'Hills Inc', 'Abshirehaven', 'elementary', '6-8', 0),
(63, 'Daugherty - Kub', 'Canton', 'charter', '6-8', 0),
(64, 'Reynolds, Koch and Collier', 'Lake Lavinialand', 'private', 'K-12', 0),
(65, 'Mante - Pfannerstill', 'West Sierraland', 'elementary', 'K-5', 0),
(66, 'Heidenreich Inc', 'Dublin', 'charter', 'K-12', 0),
(67, 'Hilll - Wisozk', 'South Deshawn', 'high', '6-8', 0),
(68, 'Waelchi, Ryan and Becker', 'Jakaylaberg', 'private', '9-12', 0),
(69, 'Buckridge, Connelly and Lemke', 'Windlertown', 'public', 'K-12', 0),
(70, 'O''Reilly, Yundt and Champlin', 'West Dashawn', 'high', 'K-12', 0),
(71, 'Sanford - Kohler', 'West Anastacio', 'middle', 'K-12', 0),
(72, 'Paucek - Bayer', 'Dickensborough', 'private', '6-8', 0),
(73, 'Grady Inc', 'Ebertworth', 'high', '9-12', 0),
(74, 'Sanford - Abbott', 'Hermannboro', 'middle', '9-12', 0),
(75, 'Rice and Sons', 'South Flavieview', 'public', 'K-12', 0),
(76, 'Nolan LLC', 'Fort Gloriaboro', 'charter', 'K-12', 0),
(77, 'Mills - Price', 'North Rossie', 'private', '6-8', 0),
(78, 'West - Hackett', 'Nicolasport', 'middle', '6-8', 0),
(79, 'Green - Kling', 'South Clement', 'middle', '9-12', 0),
(80, 'Haley and Sons', 'Lake Alishashire', 'middle', 'K-12', 0),
(81, 'Moen LLC', 'Okunevafield', 'middle', '6-8', 0),
(82, 'Barrows - Harber', 'South Cathyfurt', 'public', 'K-12', 0),
(83, 'Rau Group', 'New Haskell', 'charter', 'K-5', 0),
(84, 'Jerde, Schaden and Runolfsson', 'West Paulaville', 'private', '9-12', 0),
(85, 'Stanton - Gerlach', 'Eleanoraburgh', 'charter', 'K-12', 0),
(86, 'Kuhn, Donnelly and Keeling', 'Luettgenborough', 'public', 'K-12', 0),
(87, 'Koepp - Terry', 'North Imelda', 'private', '9-12', 0),
(88, 'Block LLC', 'Biankaside', 'high', '6-8', 0),
(89, 'Farrell Inc', 'Turcottemouth', 'public', '9-12', 0),
(90, 'Zieme, Lesch and Johnston', 'Daytona Beach', 'middle', 'K-12', 0),
(91, 'Hudson, Shanahan and Bahringer', 'Isabellefield', 'private', '9-12', 0),
(92, 'Kertzmann Inc', 'Jaedenberg', 'public', '9-12', 0),
(93, 'Rau - Williamson', 'Madisoncester', 'public', 'K-5', 0),
(94, 'Jacobi - Stark', 'Terryburgh', 'middle', 'K-12', 0),
(95, 'Stoltenberg - Rodriguez', 'Ellicott City', 'middle', '9-12', 0),
(96, 'Fisher - Hodkiewicz', 'Demondville', 'elementary', '9-12', 0),
(97, 'Hirthe and Sons', 'Arden-Arcade', 'middle', 'K-5', 0),
(98, 'Jacobs and Sons', 'Leannonshire', 'public', '9-12', 0),
(99, 'Padberg - Armstrong', 'New Lauryhaven', 'private', '9-12', 0),
(100, 'Gusikowski, Effertz and Swaniawski', 'New Susanbury', 'elementary', '9-12', 0),
(101, 'Morissette - Steuber', 'Stromanfield', 'charter', 'K-5', 0),
(102, 'Beahan and Sons', 'Fort Carolannefield', 'high', 'K-5', 0),
(103, 'Little Group', 'New Rahsaancester', 'public', '6-8', 0),
(104, 'Balistreri - Nader', 'Mesa', 'charter', '6-8', 0),
(105, 'Quigley LLC', 'Port Johnpaulcester', 'public', '9-12', 0),
(106, 'Rowe, Dare and Kemmer', 'Utica', 'private', '9-12', 0),
(107, 'Keebler, Haley and Goodwin', 'South Jermain', 'high', 'K-5', 0),
(108, 'Kub, Blick and Brakus', 'Erie', 'elementary', '9-12', 0),
(109, 'Becker - Goldner', 'Lake Zora', 'charter', 'K-5', 0)
;

-- Batch 2 of 3
INSERT INTO `schools` (`id`, `school_name`, `school_district`, `school_type`, `grade_level`, `is_deleted`) VALUES
(110, 'Boyer and Sons', 'East Reubenville', 'high', 'K-12', 0),
(111, 'Turcotte, Jerde and Brekke', 'Langworthview', 'private', 'K-5', 0),
(112, 'Hilpert LLC', 'Langoshfurt', 'public', '9-12', 0),
(113, 'Koelpin Inc', 'Brekkeberg', 'public', 'K-5', 0),
(114, 'Rice Inc', 'South Winston', 'charter', 'K-12', 0),
(115, 'Kerluke - Barrows', 'Mikelfort', 'middle', '6-8', 0),
(116, 'Purdy, Roberts and Stiedemann', 'Port Micheletown', 'public', 'K-12', 0),
(117, 'Wyman - Hoeger', 'Jonesside', 'charter', '6-8', 0),
(118, 'Fadel - Nikolaus', 'Weissnatville', 'middle', 'K-12', 0),
(119, 'Dare - Koch', 'Lake Forest', 'middle', 'K-12', 0),
(120, 'Wiza, Quigley and Beer', 'Fort Jaquan', 'public', 'K-12', 0),
(121, 'Bradtke Inc', 'Ratkefurt', 'public', '6-8', 0),
(122, 'Runolfsdottir, Langosh and Harber', 'Fort Mary', 'elementary', 'K-12', 0),
(123, 'Hand, Reichert and Kub', 'Lake Ridge', 'high', '6-8', 0),
(124, 'Bernier - Kunde', 'South Rosella', 'charter', 'K-12', 0),
(125, 'Wiza - Jakubowski', 'Harveyport', 'charter', 'K-5', 0),
(126, 'Smitham LLC', 'Lake Kristina', 'private', 'K-5', 0),
(127, 'Fahey - Daugherty', 'Lake Abagail', 'middle', 'K-5', 0),
(128, 'Boehm and Sons', 'Columbus', 'elementary', 'K-5', 0),
(129, 'Stracke Group', 'Kochville', 'private', '6-8', 0),
(130, 'Wisoky, Mayer and Walsh', 'South Howard', 'middle', '9-12', 0),
(131, 'Larkin - Klocko', 'Lake Estefaniahaven', 'elementary', 'K-12', 0),
(132, 'Torp Inc', 'New Aricstad', 'middle', '9-12', 0),
(133, 'Lang and Sons', 'South Eleazarberg', 'high', '6-8', 0),
(134, 'Sipes Group', 'Kuhicport', 'public', '9-12', 0),
(135, 'Ortiz, Spencer and Fisher', 'East Arvid', 'high', 'K-12', 0),
(136, 'McCullough, Mann and Renner', 'Candacecester', 'public', '9-12', 0),
(137, 'Pagac, Ondricka and Jones', 'Bernhardshire', 'elementary', 'K-12', 0),
(138, 'Bartoletti and Sons', 'South Bend', 'private', '9-12', 0),
(139, 'Reichel and Sons', 'West Hershelborough', 'charter', 'K-12', 0),
(140, 'Dach, McGlynn and Jakubowski', 'Mylesbury', 'private', '6-8', 0),
(141, 'DuBuque, Robel and Huels', 'Matildeville', 'private', 'K-12', 0),
(142, 'West, Dickinson and Schumm', 'Steuberstead', 'private', '6-8', 0),
(143, 'Boyle Inc', 'Kingsport', 'middle', '6-8', 0),
(144, 'Stokes Inc', 'Columbia', 'middle', 'K-5', 0),
(145, 'Walker and Sons', 'North Emmitttown', 'elementary', '9-12', 0),
(146, 'Hammes and Sons', 'Treutelstead', 'elementary', '9-12', 0),
(147, 'O''Keefe and Sons', 'Wolfview', 'charter', 'K-5', 0),
(148, 'Cormier, Reichel and Corwin', 'Potomac', 'high', '9-12', 0),
(149, 'Dietrich - Anderson', 'Alberthastad', 'middle', 'K-12', 0),
(150, 'Leannon LLC', 'Fort Maxie', 'charter', '6-8', 0),
(151, 'Cassin, Shields and Harvey', 'Rochester', 'charter', 'K-5', 0),
(152, 'Hermiston, Purdy and Keebler', 'Terre Haute', 'elementary', 'K-5', 0),
(153, 'Jaskolski - Ritchie', 'Fort Dahliaberg', 'public', 'K-5', 0),
(154, 'Kling, Yost and Larson', 'New Mathilde', 'elementary', '6-8', 0),
(155, 'Pfannerstill - Abbott', 'Port Lydaville', 'high', 'K-12', 0),
(156, 'Wisoky LLC', 'South Kittyfurt', 'charter', 'K-5', 0),
(157, 'Stanton and Sons', 'Marquardtboro', 'middle', '9-12', 0),
(158, 'Stanton and Sons', 'South Willowstad', 'public', 'K-12', 0),
(159, 'Halvorson LLC', 'Eugeneton', 'public', 'K-5', 0),
(160, 'Hermiston, Schamberger and Pfannerstill', 'North Rupertboro', 'elementary', 'K-12', 0),
(161, 'Powlowski - Marks', 'Mittieworth', 'high', 'K-5', 0),
(162, 'Abernathy Group', 'Sanfordstead', 'private', '6-8', 0),
(163, 'Bailey Inc', 'Gorczanyfort', 'public', '9-12', 0),
(164, 'Flatley Inc', 'Violetcester', 'high', '9-12', 0),
(165, 'Roob - Parker', 'North Isaias', 'elementary', '6-8', 0),
(166, 'Sawayn Group', 'Giovanitown', 'elementary', 'K-5', 0),
(167, 'Flatley Group', 'Fort Genovevaberg', 'high', 'K-12', 0),
(168, 'Goodwin - Hyatt', 'Lawton', 'private', 'K-5', 0),
(169, 'Lakin Group', 'Peoria', 'public', 'K-5', 0),
(170, 'Gerlach, Schuppe and Veum', 'Stiedemannbury', 'elementary', 'K-12', 0),
(171, 'Green, Waters and Crooks', 'Lake Brandon', 'charter', '6-8', 0),
(172, 'Jenkins, Bosco and Boyle', 'Andersonchester', 'public', 'K-5', 0),
(173, 'Predovic - Renner', 'Tadland', 'private', '6-8', 0),
(174, 'Pouros - Balistreri', 'Chapel Hill', 'charter', 'K-12', 0),
(175, 'Larson, Wiza and Crona', 'Rancho Cucamonga', 'elementary', 'K-5', 0),
(176, 'Langosh, Daugherty and Marks', 'Lockmanville', 'high', '9-12', 0),
(177, 'Bergstrom - Hamill', 'Port Imelda', 'private', 'K-5', 0),
(178, 'Connelly, Rau and Bogisich', 'Fredside', 'public', '9-12', 0),
(179, 'Schulist and Sons', 'League City', 'high', 'K-5', 0),
(180, 'Green Group', 'Kenosha', 'high', 'K-5', 0),
(181, 'Cruickshank - Lebsack', 'Vinceberg', 'charter', '9-12', 0),
(182, 'Hoeger, Stanton and Jaskolski', 'Bryonborough', 'private', '9-12', 0),
(183, 'Welch - Mohr', 'West Kiannatown', 'elementary', '6-8', 0),
(184, 'Lesch, Lindgren and Ortiz', 'East Kaelyn', 'high', '6-8', 0),
(185, 'Ebert Group', 'Mrazfield', 'charter', 'K-5', 0),
(186, 'Schuster - Kirlin', 'Williamsonmouth', 'charter', '9-12', 0),
(187, 'Mayer - Renner', 'Lake Marcelino', 'high', 'K-5', 0),
(188, 'Stokes, Turner and Paucek', 'Lake Baronmouth', 'public', 'K-12', 0),
(189, 'Harris - Heller', 'Sawaynchester', 'middle', 'K-12', 0),
(190, 'Erdman, Runte and Heidenreich', 'Dooleyfurt', 'private', '6-8', 0),
(191, 'Abernathy Inc', 'Niagara Falls', 'public', 'K-12', 0),
(192, 'Connelly, Stracke and Shanahan', 'Elmoreton', 'private', 'K-5', 0),
(193, 'Spencer Group', 'North Sammyville', 'elementary', '6-8', 0),
(194, 'Huel - Streich', 'Fountain Valley', 'public', '9-12', 0),
(195, 'Cole, Carroll and Stokes', 'East Harrison', 'charter', '6-8', 0),
(196, 'Schmidt, Weimann and Mayer', 'Roseville', 'private', '9-12', 0),
(197, 'Wunsch - Kertzmann', 'Lake Orin', 'middle', '6-8', 0),
(198, 'Tillman LLC', 'Watsonville', 'middle', '9-12', 0),
(199, 'Conroy - Koss', 'South Richmondboro', 'private', 'K-12', 0),
(200, 'Hayes Group', 'Boylebury', 'public', 'K-5', 0),
(201, 'Beahan Group', 'Lake Keven', 'middle', '6-8', 0),
(202, 'Koepp Inc', 'Port Julien', 'middle', 'K-12', 0),
(203, 'Zboncak, Bartell and Dicki', 'Bowie', 'private', 'K-12', 0),
(204, 'Ward, Murazik and Reilly', 'Elnaside', 'elementary', '9-12', 0),
(205, 'Greenfelder LLC', 'New Braunfels', 'public', '6-8', 0),
(206, 'Crist, Kling and Rath', 'West Uriel', 'elementary', 'K-5', 0),
(207, 'Upton LLC', 'Apple Valley', 'elementary', '9-12', 0),
(208, 'Moen, Gleason and Kuhn', 'Fort Vivian', 'elementary', 'K-12', 0),
(209, 'Beer Inc', 'South Margret', 'middle', '9-12', 0)
;

-- Batch 3 of 3
INSERT INTO `schools` (`id`, `school_name`, `school_district`, `school_type`, `grade_level`, `is_deleted`) VALUES
(210, 'Walsh, Schamberger and Powlowski', 'Derrickworth', 'high', '9-12', 0),
(211, 'Padberg, Littel and Prohaska', 'Julianashire', 'charter', '6-8', 0),
(212, 'Bayer - Schamberger', 'Linden', 'middle', 'K-5', 0),
(213, 'Zieme, Runolfsson and O''Conner', 'Schadenborough', 'public', '9-12', 0),
(214, 'Durgan LLC', 'New Daytonchester', 'elementary', '6-8', 0),
(215, 'Kuphal - Bergstrom', 'Jacksonville', 'elementary', 'K-12', 0),
(216, 'Rempel LLC', 'Suffolk', 'charter', '9-12', 0),
(217, 'Bashirian and Sons', 'Lynwood', 'elementary', '9-12', 0),
(218, 'Brekke, Huels and Smith', 'West Ashlee', 'high', '6-8', 0),
(219, 'Runolfsson and Sons', 'Hellerboro', 'public', '9-12', 0),
(220, 'Mayer, Simonis and Littel', 'North Madysonstead', 'private', 'K-5', 0),
(221, 'Lind and Sons', 'Port Callieton', 'elementary', 'K-5', 0),
(222, 'Hamill - Marks', 'New Jettiemouth', 'high', '9-12', 0),
(223, 'Luettgen - Cremin', 'Pearlhaven', 'elementary', '6-8', 0),
(224, 'Dach, Moore and Smith', 'Deliacester', 'high', 'K-5', 0),
(225, 'Champlin, Littel and Collins', 'Carterside', 'private', 'K-5', 0),
(226, 'Nicolas, Torphy and Bauch', 'Brionnaborough', 'charter', '6-8', 0),
(227, 'Johns, Hane and Donnelly', 'Litzyville', 'middle', '6-8', 0),
(228, 'Walter Group', 'Konopelskichester', 'high', 'K-5', 0),
(229, 'Brown, Bergnaum and Glover', 'South Vada', 'elementary', 'K-5', 0),
(230, 'Rutherford - Jast', 'New Abagail', 'middle', '6-8', 0),
(231, 'Ziemann - Hettinger', 'Lake Rita', 'charter', '6-8', 0),
(232, 'Corkery - Hilll', 'Nicolasworth', 'elementary', 'K-12', 0),
(233, 'Gleason, Lemke and Harris', 'South Alfonzoside', 'elementary', '9-12', 0),
(234, 'Runte Inc', 'Fort Franceschester', 'middle', 'K-5', 0),
(235, 'Hilll and Sons', 'Port Halliefurt', 'elementary', 'K-5', 0),
(236, 'Dach, Dibbert and Kub', 'San Clemente', 'charter', 'K-5', 0),
(237, 'Hammes, Ward and Dickinson', 'New Jo', 'middle', 'K-5', 0),
(238, 'Labadie Group', 'Minervafort', 'public', 'K-12', 0),
(239, 'Mills - O''Hara', 'Doral', 'middle', 'K-5', 0),
(240, 'Rath - Stehr', 'Gunnercester', 'private', '6-8', 0),
(241, 'Hagenes, Reilly and Auer', 'Danielhaven', 'private', '9-12', 0),
(242, 'Cormier, Johnston and Greenfelder', 'Lake Claudeton', 'public', 'K-12', 0),
(243, 'Runte - Deckow', 'Cutler Bay', 'middle', '9-12', 0),
(244, 'Kozey - Harris', 'Fort Cody', 'high', 'K-5', 0),
(245, 'Reinger LLC', 'Celiaport', 'elementary', 'K-12', 0),
(246, 'Wintheiser, Wolff and Paucek', 'Leonelborough', 'middle', '9-12', 0),
(247, 'Kilback Group', 'New Josue', 'middle', 'K-12', 0),
(248, 'Anderson, Klein and Legros', 'Connieberg', 'public', '6-8', 0),
(249, 'Bogan - Goldner', 'Corpus Christi', 'public', '6-8', 0),
(250, 'Braun - Gislason', 'East Johan', 'private', '6-8', 0),
(251, 'Wunsch, Gusikowski and Strosin', 'Julescester', 'middle', 'K-5', 0),
(252, 'Littel Inc', 'McCulloughton', 'private', '6-8', 0),
(253, 'Pouros, Jenkins and Bergnaum', 'Wilmerport', 'middle', 'K-12', 0),
(254, 'O''Reilly, Glover and Collier', 'New Vivianbury', 'elementary', 'K-5', 0),
(255, 'Hackett Inc', 'Rogerschester', 'middle', 'K-12', 0),
(256, 'Nitzsche - Hyatt', 'Port Juston', 'elementary', 'K-5', 0),
(257, 'Keebler Group', 'West Elenoraland', 'elementary', 'K-5', 0),
(258, 'Willms, McGlynn and Sauer', 'Port Queenieview', 'charter', 'K-12', 0),
(259, 'Zulauf Group', 'Gerholdport', 'high', '9-12', 0)
;